const { log } = require("console");

function seRompe(){
    return 4 + i;
}

try{
    reRompe();
    
}catch(err){
    console.log('Algo se rompio');
    console.error(err.message);
    console.log('No pasa nada, lo hemos atrapado');
}
